parameters:
# listing different ways to define parameters with / without default values
- jobDesc: ''
- name: env
  default: ''
- name: appName
  type: string
  default: ''

jobs:
- deployment: Deploy
  displayName: '${{ parameters.jobDesc }}'
  pool:
    vmImage: 'ubuntu-16.04'
  environment: ${{ parameters.env }}
  variables:
  - group: 'Release'
  strategy:
    runOnce:
      deploy:
        steps:
        - download: current
          artifact: drop
        - task: AzureWebApp@1
          displayName: 'Azure App Service Deploy: website'
          inputs:
            azureSubscription: 'Resource Manager - Tailspin - Space Game'
            appName: '${{ parameters.appName }}'
            package: '$(Pipeline.Workspace)/drop/$(buildConfiguration)/*.zip'