trigger:
- '*'

variables:
  buildConfiguration: 'Release'
  releaseBranchName: 'release'

schedules:
- cron: '0  3 * * *'
  displayName: 'Deploy at 3:00AM daily'
  branches:
    include:
      - release
  always: false

stages:
- stage: 'Build'
  displayName: 'Build web app'
  jobs: 
  - job: 'Build'
    displayName: 'Build app'
    pool:
      vmImage: 'ubuntu-16.04'
      demands:
        - npm

    variables:
      wwwrootDir: 'Tailspin.SpaceGame.Web/wwwroot'
      dotnetSdkVersion: '3.1.100'

    steps:
    - task: UseDotNet@2
      displayName: 'Use .NET Core SDK $(dotnetSdkVersion)'
      inputs:
        version: '$(dotnetSdkVersion)'

    - task: Npm@1
      displayName: 'Run npm install'
      inputs:
        verbose: false

    - script: './node_modules/.bin/node-sass $(wwwrootDir) --output $(wwwrootDir)'
      displayName: 'Compile Sass assets'

    - task: gulp@1
      displayName: 'Run gulp tasks'

    - script: 'echo "$(Build.DefinitionName), $(Build.BuildId), $(Build.BuildNumber)" > buildinfo.txt'
      displayName: 'Write build info'
      workingDirectory: $(wwwrootDir)

    - task: DotNetCoreCLI@2
      displayName: 'Restore project dependencies'
      inputs:
        command: 'restore'
        projects: '**/*.csproj'

    - task: DotNetCoreCLI@2
      displayName: 'Build the project - $(buildConfiguration)'
      inputs:
        command: 'build'
        arguments: '--no-restore --configuration $(buildConfiguration)'
        projects: '**/*.csproj'

    - task: DotNetCoreCLI@2
      displayName: 'Publish the project - $(buildConfiguration)'
      inputs:
        command: 'publish'
        projects: '**/*.csproj'
        publishWebProjects: false
        arguments: '--no-build --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/$(buildConfiguration)'
        zipAfterPublish: true

    - publish: '$(Build.ArtifactStagingDirectory)'
      artifact: drop

- stage: 'Dev'
  displayName: 'Deploy to Dev env'
  dependsOn: Build
  condition: | 
    and 
    (
      succeeded(),
      eq(variables['Build.SourceBranchName'], variables['releaseBranchName'])
    )
  jobs:
  - template: template/deploy-job.yml
    parameters:
      displayName: 'Job - Deploy to Dev env'
      env: dev
      appName: '$(WebAppNameDev)'

- stage: 'Test'
  displayName: 'Deploy to Test env'
  dependsOn: Dev
  # condition: eq(variables['Build.Reason'], 'Schedule')
  jobs:
  - template: template/deploy-job.yml
    parameters:
      displayName: 'Job - Deploy to Test env'
      env: test
      appName: '$(WebAppNameTest)'

- stage: 'Staging'
  displayName: 'Deploy to Staging env'
  dependsOn: Test
  jobs:
  - template: template/deploy-job.yml
    parameters:
      displayName: 'Job - Deploy to Staging env'
      env: staging
      appName: '$(WebAppNameStaging)'

